version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains AirBNB listings.
    columns:
      - name: listing_id
        description: Primary key for the listing
        tests: 
          - unique
          - not_null
      - name: host_id
        description: The host's id. References the hosts table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        tests:
          - accepted_values:
              values: ['Entire home/apt',
                       'Private room',
                       'Shared room',
                       'Hotel room']
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value
  - name: dim_hosts_cleansed
    description: Cleansed table which containts Airbnb hosts.
    columns:
      - name: host_id
        description: Primary key for the host.
      - name: host_name
        description: Name of the host.
      - name: is_superhost
        description: Is the host a super host.
  - name: dim_listings_with_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('demo_dbt', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50 
              max_value: 500

        
